server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://ecommerce-postgres:5432/order_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka