server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://ecommerce-postgres:5432/product_db
    username: postgres
    password: postgres

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka